# Required files 
query_proteome: "data/wmel.faa"
accession_list: "data/wmel_ALL.txt"

# Required values 
microbe_id: '163164'
taxon_id: '766'
work_dir: 'outputs'
max_genomes: '500'

# Logging
log_path: 'logs/'

#Resource values
mmseq_threads: '80'