# Required files 
query_proteome: "data/hpylori_proteome.faa"
accession_list: "data/helicobacter_ALL.txt"

# Required values 
microbe_id: '85962'
taxon_id: '213849'
work_dir: 'outputs'
max_genomes: '1000'

# Logging
log_path: 'logs/'

#Resource values
mmseq_threads: '40'