# Required files 
query_proteome: "data/hpylori_26695.faa"
accession_list: "data/hp_noncandidate_accessions.txt"

# Required values 
microbe_id: '85962'
taxon_id: '1236'
work_dir: 'hp_curated_nonc_outputs'
max_genomes: '200'
hyphy_e_number: '0.04' # sets hyphy pre-process.bf acceptance of low homology sequences (lower float = less stringent)

# Logging
log_path: 'hp_curated_nonc_outputs/logs/'

#Resource values
mmseq_threads: '80'

#Other options
max_ortho_seqs: '100'