# Required files 
query_proteome: "data/hpylori_26695.faa"
accession_list: "data/hp_all_candidates.txt"

# Required values 
microbe_id: '85962'
taxon_id: '72293'
taxon_ids: ['3031852']
work_dir: 'hp_outputs'
max_genomes: '200'
hyphy_e_number: '0.04' # sets hyphy pre-process.bf acceptance of low homology sequences (lower float = less stringent)
nltk_data_dir: 'nlp_model_data'

# Logging
log_path: 'hp_outputs/logs/'

#Resource values
mmseq_threads: '80'

#Other options
max_ortho_seqs: '100'