# Required files 
query_proteome: "data/wmel.faa"
accession_list: "data/wmel_ALL.txt"

# Required values 
microbe_id: '163164'
taxon_id: '28211'
work_dir: 'wmel_curated_outputs'
max_genomes: '200'
hyphy_e_number: '0.02' # sets hyphy pre-process.bf acceptance of low homology sequences (lower float = less stringent)

# Logging
log_path: 'wmel_curated_outputs/logs/'

#Resource values
mmseq_threads: '80'

#Other options
max_ortho_seqs: '100'