executor: slurm
use-conda: False
jobs: 100 # Have up to N jobs submitted at any given time
latency-wait: 30 # Wait N seconds for output files due to latency
retries: 2 # Retry jobs N times.
max-jobs-per-second: 5
max-status-checks-per-second: 5
keep-going: True

# These resources will be applied to all rules. Can be overriden on a per-rule basis below.
default-resources:
  slurm_partition: "medium"
  slurm_account: # Same as sbatch -A. Not all clusters use this.
  runtime: 180 # In minutes
  mem_mb: 30000 # In MB

set-resources:
  download_genomes:
    slurm_partition: "long"
    slurm_account: # Same as sbatch -A. Not all clusters use this.
    runtime: 1440 # In minutes
  mmseq_rbh:
    slurm_partition: "short"
    slurm_account: # Same as sbatch -A. Not all clusters use this.
    runtime: 30 # In minutes
  collect_orthologs:
    slurm_partition: "short"
    slurm_accout: # Same as sbatch -A. Not all clusters use this.
    runtime: 60 # In minutes
    cpus_per_task: 1 
    retries: 5 
    jobs: 50
  hyphy_codon_preprocess:
    slurm_partition: "medium"
    slurm_account: # Same as sbatch -A. Not all clusters use this.
    runtime: 120 # In minutes
    mem_mb: 60000 # In MB
  iqtree:
    slurm_partition: "medium"
    slurm_account: # Same as sbatch -A. Not all clusters use this.
    runtime: 600 # In minutes
  absrel:
    slurm_partition: "medium"
    slurm_account: # Same as sbatch -A. Not all clusters use this.
    runtime: 600 # In minutes

set-threads:
  download_genomes: 1
  mmseq_rbh: 80
  collect_orthologs: 1
  iqtree: 20
  absrel: 1

